### Get all contacts from localhost
GET http://localhost:3000/contacts

### Get contact by Id
GET http://localhost:3000/contacts/655215f9c8d9fca069df0354

### Create a contact
POST http://localhost:3000/contacts
content-type: application/json

{
    "email":"johndoe@example.com",
    "birthday":"March 5 1995",
    "favoriteColor":"White",
    "firstName":"John",
    "lastName":"Doe"
}

### PUT contact
PUT http://localhost:3000/contacts/6552190ec8d9fca069df0359
content-type: application/json

{
    "firstName": "Brian",
    "lastName": "Henshaw",
    "email": "henjohn@example.com",
    "favoriteColor": "Violet",
    "birthday": "11/04/1990"
}

### DELETE contact
DEELTE http://localhost:3000/contacts/656cd8c735c2343efbf0d620


// TESTING IN PRODUCTION USING REST CLIENT

### Get Single
GET https://project1-cdyb.onrender.com/contacts/

### Get contact by Id
GET https://project1-cdyb.onrender.com/contacts/655215f9c8d9fca069df0354

### Create a contact
POST https://project1-cdyb.onrender.com/contacts
content-type: application/json

{
    "email":"administrator@admin.com",
    "birthday":"August 10 2003",
    "favoriteColor":"Red",
    "firstName":"Super",
    "lastName":"Administrator"
}

### PUT contact
PUT https://project1-cdyb.onrender.com/contacts/6552190ec8d9fca069df0359
content-type: application/json

{
    "firstName": "Hendrick",
    "lastName": "Henshaw",
    "email": "henjohn@example.com",
    "favoriteColor": "Violet",
    "birthday": "11/04/1990"
}

### DELETE contact
DELETE https://project1-cdyb.onrender.com/contacts/656cb83feb5c5b4ab420b4fd